version: '2'
services:
    drkiq:
        build: .
        # Link to containers in another service 
        links:
            - postgres
            - redis
        # http://container-solutions.com/understanding-volumes-docker/
        volumes:
            - .:/drkiq
        ports:
        # always explicitly specifying your port mappings as strings.
            - '8000:8000'
        # Compose expects each line in an env file to be in VAR=VAL format. 
        # Lines beginning with # (i.e. comments) are ignored, as are blank lines.
        env_file:
            - .drkiq.env
    sidekiq:
        build: .
        # Override the default command.
        command: bundle exec sidekiq -C config/sidekiq.yml
        links:
            - postgres
            - redis
        volumes:
            - .:/drkiq
        env_file:
            - .drkiq.env
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: drkiq
            POSTGRES_PASSWORD: yourpassword
        ports:
            # Override the default
            - '5432:5432'
        volumes:
            - drkiq-postgres:/var/lib/postgresql/data
    redis:
        image: redis
        ports:
            # Override the default
            - '6379:6379'
        volumes:
            - drkiq-redis:/var/lib/redis/data
# https://docs.docker.com/compose/compose-file/#version-2
volumes:
    drkiq-postgres:
        driver: local
    drkiq-redis:
        driver: local
